# Generated by Django 5.2 on 2026-01-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['publish_date'], name='listings_li_publish_f09bf8_idx'),
        ),
    ]
